### ISSUE TITLE
Create "bonk" command

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/discord-bot#14]
This command will temporarily timeout a member

**Comment by cajthamlmatej** [comment]
Maybe we should do "lightweight" voting system on this one. Just two more reactions and the person would be bonked.

**Comment by H7KZ** [comment]
I strongly disagree. Some people could create a plot at someone so that he never chats again. Not a well-advised idea for a bot that is focused on school and studies.

**Comment by 3ncy** [comment]
> Maybe we should do "lightweight" voting system on this one. Just two more reactions and the person would be bonked.

This should be configurable option, not hardcoded
But if you want it hardcoded, I'd personally go for 3 reactions, cause often there aren't even 5 people in a convo, but 2 on the other hand sounds a bit too low.  
I'd say only testing will tell what is the optimal number
